//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDevSysGraphical {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetDevSysGraphical.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed successfully !.
        /// </summary>
        internal static string BackupCompletionWatcher_TextFinish {
            get {
                return ResourceManager.GetString("BackupCompletionWatcher.TextFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Complete : .
        /// </summary>
        internal static string BackupCompletionWatcher_TittleFinish {
            get {
                return ResourceManager.GetString("BackupCompletionWatcher.TittleFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blocking process has been detected. Backups are paused.
        /// </summary>
        internal static string BackupWatcher_TextPopupFind {
            get {
                return ResourceManager.GetString("BackupWatcher.TextPopupFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All blocking processes have been resolved. Backups are resumed..
        /// </summary>
        internal static string BackupWatcher_TextPopupResolve {
            get {
                return ResourceManager.GetString("BackupWatcher.TextPopupResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking process detected.
        /// </summary>
        internal static string BackupWatcher_TittlePopupFind {
            get {
                return ResourceManager.GetString("BackupWatcher.TittlePopupFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking Process Resolved.
        /// </summary>
        internal static string BackupWatcher_TittlePopupResolve {
            get {
                return ResourceManager.GetString("BackupWatcher.TittlePopupResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Config_Apply {
            get {
                return ResourceManager.GetString("Config.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocker processes : if detected backup is interrupted.
        /// </summary>
        internal static string Config_Blocker1 {
            get {
                return ResourceManager.GetString("Config.Blocker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a Process name :.
        /// </summary>
        internal static string Config_Blocker2 {
            get {
                return ResourceManager.GetString("Config.Blocker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSave Configuration.
        /// </summary>
        internal static string Config_Crypto1 {
            get {
                return ResourceManager.GetString("Config.Crypto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSave Path :.
        /// </summary>
        internal static string Config_Crypto2 {
            get {
                return ResourceManager.GetString("Config.Crypto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSave extensions to encrypt :.
        /// </summary>
        internal static string Config_Crypto3 {
            get {
                return ResourceManager.GetString("Config.Crypto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string Config_Crypto4 {
            get {
                return ResourceManager.GetString("Config.Crypto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of heavy files.
        /// </summary>
        internal static string Config_FileSize0 {
            get {
                return ResourceManager.GetString("Config.FileSize0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string Config_FileSize1 {
            get {
                return ResourceManager.GetString("Config.FileSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        internal static string Config_FileSize2 {
            get {
                return ResourceManager.GetString("Config.FileSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change localization.
        /// </summary>
        internal static string Config_Languages1 {
            get {
                return ResourceManager.GetString("Config.Languages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language :.
        /// </summary>
        internal static string Config_Languages2 {
            get {
                return ResourceManager.GetString("Config.Languages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files Configuration.
        /// </summary>
        internal static string Config_Log1 {
            get {
                return ResourceManager.GetString("Config.Log1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Log Path :.
        /// </summary>
        internal static string Config_Log2 {
            get {
                return ResourceManager.GetString("Config.Log2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Log Path :.
        /// </summary>
        internal static string Config_Log3 {
            get {
                return ResourceManager.GetString("Config.Log3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Extension type :.
        /// </summary>
        internal static string Config_Log4 {
            get {
                return ResourceManager.GetString("Config.Log4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority files.
        /// </summary>
        internal static string Config_Priority1 {
            get {
                return ResourceManager.GetString("Config.Priority1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension of files to prioritize:.
        /// </summary>
        internal static string Config_Priority3 {
            get {
                return ResourceManager.GetString("Config.Priority3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Config_Reset {
            get {
                return ResourceManager.GetString("Config.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to backups save file.
        /// </summary>
        internal static string Config_SavePath1 {
            get {
                return ResourceManager.GetString("Config.SavePath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the path to your backups save file :.
        /// </summary>
        internal static string Config_SavePath2 {
            get {
                return ResourceManager.GetString("Config.SavePath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote interface.
        /// </summary>
        internal static string Config_Serv0 {
            get {
                return ResourceManager.GetString("Config.Serv0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on the server:.
        /// </summary>
        internal static string Config_Serv1 {
            get {
                return ResourceManager.GetString("Config.Serv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files.
        /// </summary>
        internal static string Config_Tab1 {
            get {
                return ResourceManager.GetString("Config.Tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSave.
        /// </summary>
        internal static string Config_Tab2 {
            get {
                return ResourceManager.GetString("Config.Tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Config_Tab3 {
            get {
                return ResourceManager.GetString("Config.Tab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocker Process.
        /// </summary>
        internal static string Config_Tab4 {
            get {
                return ResourceManager.GetString("Config.Tab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Paths.
        /// </summary>
        internal static string Config_Tab5 {
            get {
                return ResourceManager.GetString("Config.Tab5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        internal static string Config_Themes1 {
            get {
                return ResourceManager.GetString("Config.Themes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Config_Themes2 {
            get {
                return ResourceManager.GetString("Config.Themes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome !.
        /// </summary>
        internal static string Home1 {
            get {
                return ResourceManager.GetString("Home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings ?.
        /// </summary>
        internal static string ResetConfig {
            get {
                return ResourceManager.GetString("ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save done.
        /// </summary>
        internal static string RunTaskView11 {
            get {
                return ResourceManager.GetString("RunTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saves done.
        /// </summary>
        internal static string RunTaskView12 {
            get {
                return ResourceManager.GetString("RunTaskView12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Blocker process is in use (your backups will be done when the process is closed).
        /// </summary>
        internal static string RunTaskView4 {
            get {
                return ResourceManager.GetString("RunTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processus Error.
        /// </summary>
        internal static string RunTaskView5 {
            get {
                return ResourceManager.GetString("RunTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the saves are done.
        /// </summary>
        internal static string RunTaskView6 {
            get {
                return ResourceManager.GetString("RunTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Selector1 {
            get {
                return ResourceManager.GetString("Selector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves.
        /// </summary>
        internal static string Selector2 {
            get {
                return ResourceManager.GetString("Selector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Selector3 {
            get {
                return ResourceManager.GetString("Selector3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceedings are already underway..
        /// </summary>
        internal static string StartupPopup1 {
            get {
                return ResourceManager.GetString("StartupPopup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a task.
        /// </summary>
        internal static string Task_Add_Title {
            get {
                return ResourceManager.GetString("Task.Add.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a task.
        /// </summary>
        internal static string Task_AddButton {
            get {
                return ResourceManager.GetString("Task.AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Task_Apply {
            get {
                return ResourceManager.GetString("Task.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Task_Cancel {
            get {
                return ResourceManager.GetString("Task.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Task_Delete {
            get {
                return ResourceManager.GetString("Task.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task deleted successfully.
        /// </summary>
        internal static string Task_DeleteInfo {
            get {
                return ResourceManager.GetString("Task.DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a task.
        /// </summary>
        internal static string Task_Edit_Title {
            get {
                return ResourceManager.GetString("Task.Edit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Task_Grid_Delete {
            get {
                return ResourceManager.GetString("Task.Grid.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Task_Grid_Edit {
            get {
                return ResourceManager.GetString("Task.Grid.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Task_Grid_ID {
            get {
                return ResourceManager.GetString("Task.Grid.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Task_Grid_Name {
            get {
                return ResourceManager.GetString("Task.Grid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Task_Grid_Select {
            get {
                return ResourceManager.GetString("Task.Grid.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Task_Grid_Source {
            get {
                return ResourceManager.GetString("Task.Grid.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Task_Grid_Target {
            get {
                return ResourceManager.GetString("Task.Grid.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Task_Grid_Type {
            get {
                return ResourceManager.GetString("Task.Grid.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch every tasks.
        /// </summary>
        internal static string Task_LaunchAll {
            get {
                return ResourceManager.GetString("Task.LaunchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch all selected tasks.
        /// </summary>
        internal static string Task_LaunchSelect {
            get {
                return ResourceManager.GetString("Task.LaunchSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem: source doesn&apos;t exist.
        /// </summary>
        internal static string Task_Popup_Add1 {
            get {
                return ResourceManager.GetString("Task.Popup.Add1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem: target doesn&apos;t exist.
        /// </summary>
        internal static string Task_Popup_Add2 {
            get {
                return ResourceManager.GetString("Task.Popup.Add2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem: source and target doesn&apos;t exist.
        /// </summary>
        internal static string Task_Popup_Add3 {
            get {
                return ResourceManager.GetString("Task.Popup.Add3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all the entries.
        /// </summary>
        internal static string Task_Popup_Add4 {
            get {
                return ResourceManager.GetString("Task.Popup.Add4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Task_Popup_Out {
            get {
                return ResourceManager.GetString("Task.Popup.Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string Task_Popup_Warning {
            get {
                return ResourceManager.GetString("Task.Popup.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string Task_Prompt1 {
            get {
                return ResourceManager.GetString("Task.Prompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Path :.
        /// </summary>
        internal static string Task_Prompt2 {
            get {
                return ResourceManager.GetString("Task.Prompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Path :.
        /// </summary>
        internal static string Task_Prompt3 {
            get {
                return ResourceManager.GetString("Task.Prompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Task_Type1 {
            get {
                return ResourceManager.GetString("Task.Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        internal static string Task_Type2 {
            get {
                return ResourceManager.GetString("Task.Type2", resourceCulture);
            }
        }
    }
}
