//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDevSysGraphical {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetDevSysGraphical.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string Config_Apply {
            get {
                return ResourceManager.GetString("Config.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocker processes : if detected backup is interrupted.
        /// </summary>
        internal static string Config_Blocker1 {
            get {
                return ResourceManager.GetString("Config.Blocker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert a Process name :.
        /// </summary>
        internal static string Config_Blocker2 {
            get {
                return ResourceManager.GetString("Config.Blocker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSave Configuration.
        /// </summary>
        internal static string Config_Crypto1 {
            get {
                return ResourceManager.GetString("Config.Crypto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSave Path :.
        /// </summary>
        internal static string Config_Crypto2 {
            get {
                return ResourceManager.GetString("Config.Crypto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSave extensions to encrypt :.
        /// </summary>
        internal static string Config_Crypto3 {
            get {
                return ResourceManager.GetString("Config.Crypto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions.
        /// </summary>
        internal static string Config_Crypto4 {
            get {
                return ResourceManager.GetString("Config.Crypto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size of heavy files.
        /// </summary>
        internal static string Config_FileSize0 {
            get {
                return ResourceManager.GetString("Config.FileSize0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size:.
        /// </summary>
        internal static string Config_FileSize1 {
            get {
                return ResourceManager.GetString("Config.FileSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit:.
        /// </summary>
        internal static string Config_FileSize2 {
            get {
                return ResourceManager.GetString("Config.FileSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change localization.
        /// </summary>
        internal static string Config_Languages1 {
            get {
                return ResourceManager.GetString("Config.Languages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a language :.
        /// </summary>
        internal static string Config_Languages2 {
            get {
                return ResourceManager.GetString("Config.Languages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log Files Configuration.
        /// </summary>
        internal static string Config_Log1 {
            get {
                return ResourceManager.GetString("Config.Log1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily Log Path :.
        /// </summary>
        internal static string Config_Log2 {
            get {
                return ResourceManager.GetString("Config.Log2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real-Time Log Path :.
        /// </summary>
        internal static string Config_Log3 {
            get {
                return ResourceManager.GetString("Config.Log3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs Extension type :.
        /// </summary>
        internal static string Config_Log4 {
            get {
                return ResourceManager.GetString("Config.Log4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority files.
        /// </summary>
        internal static string Config_Priority1 {
            get {
                return ResourceManager.GetString("Config.Priority1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension of files to prioritize:.
        /// </summary>
        internal static string Config_Priority3 {
            get {
                return ResourceManager.GetString("Config.Priority3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        internal static string Config_Reset {
            get {
                return ResourceManager.GetString("Config.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path to backups save file.
        /// </summary>
        internal static string Config_SavePath1 {
            get {
                return ResourceManager.GetString("Config.SavePath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert the path to your backups save file :.
        /// </summary>
        internal static string Config_SavePath2 {
            get {
                return ResourceManager.GetString("Config.SavePath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remote interface.
        /// </summary>
        internal static string Config_Serv0 {
            get {
                return ResourceManager.GetString("Config.Serv0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Turn on the server:.
        /// </summary>
        internal static string Config_Serv1 {
            get {
                return ResourceManager.GetString("Config.Serv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log Files.
        /// </summary>
        internal static string Config_Tab1 {
            get {
                return ResourceManager.GetString("Config.Tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSave.
        /// </summary>
        internal static string Config_Tab2 {
            get {
                return ResourceManager.GetString("Config.Tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Config_Tab3 {
            get {
                return ResourceManager.GetString("Config.Tab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocker Process.
        /// </summary>
        internal static string Config_Tab4 {
            get {
                return ResourceManager.GetString("Config.Tab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Paths.
        /// </summary>
        internal static string Config_Tab5 {
            get {
                return ResourceManager.GetString("Config.Tab5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App theme.
        /// </summary>
        internal static string Config_Themes1 {
            get {
                return ResourceManager.GetString("Config.Themes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme:.
        /// </summary>
        internal static string Config_Themes2 {
            get {
                return ResourceManager.GetString("Config.Themes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome !.
        /// </summary>
        internal static string Home1 {
            get {
                return ResourceManager.GetString("Home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to reset all settings ?.
        /// </summary>
        internal static string ResetConfig {
            get {
                return ResourceManager.GetString("ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save done.
        /// </summary>
        internal static string RunTaskView11 {
            get {
                return ResourceManager.GetString("RunTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à saves done.
        /// </summary>
        internal static string RunTaskView12 {
            get {
                return ResourceManager.GetString("RunTaskView12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Blocker process is in use (your backups will be done when the process is closed).
        /// </summary>
        internal static string RunTaskView4 {
            get {
                return ResourceManager.GetString("RunTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Processus Error.
        /// </summary>
        internal static string RunTaskView5 {
            get {
                return ResourceManager.GetString("RunTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All the saves are done.
        /// </summary>
        internal static string RunTaskView6 {
            get {
                return ResourceManager.GetString("RunTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        internal static string Selector1 {
            get {
                return ResourceManager.GetString("Selector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saves.
        /// </summary>
        internal static string Selector2 {
            get {
                return ResourceManager.GetString("Selector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string Selector3 {
            get {
                return ResourceManager.GetString("Selector3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proceedings are already underway..
        /// </summary>
        internal static string StartupPopup1 {
            get {
                return ResourceManager.GetString("StartupPopup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a task.
        /// </summary>
        internal static string Task_Add_Title {
            get {
                return ResourceManager.GetString("Task.Add.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a task.
        /// </summary>
        internal static string Task_AddButton {
            get {
                return ResourceManager.GetString("Task.AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string Task_Apply {
            get {
                return ResourceManager.GetString("Task.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Task_Cancel {
            get {
                return ResourceManager.GetString("Task.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result.
        /// </summary>
        internal static string Task_Delete {
            get {
                return ResourceManager.GetString("Task.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task deleted successfully.
        /// </summary>
        internal static string Task_DeleteInfo {
            get {
                return ResourceManager.GetString("Task.DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit a task.
        /// </summary>
        internal static string Task_Edit_Title {
            get {
                return ResourceManager.GetString("Task.Edit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Task_Grid_Delete {
            get {
                return ResourceManager.GetString("Task.Grid.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        internal static string Task_Grid_Edit {
            get {
                return ResourceManager.GetString("Task.Grid.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        internal static string Task_Grid_ID {
            get {
                return ResourceManager.GetString("Task.Grid.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Task_Grid_Name {
            get {
                return ResourceManager.GetString("Task.Grid.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        internal static string Task_Grid_Select {
            get {
                return ResourceManager.GetString("Task.Grid.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string Task_Grid_Source {
            get {
                return ResourceManager.GetString("Task.Grid.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target.
        /// </summary>
        internal static string Task_Grid_Target {
            get {
                return ResourceManager.GetString("Task.Grid.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string Task_Grid_Type {
            get {
                return ResourceManager.GetString("Task.Grid.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch every tasks.
        /// </summary>
        internal static string Task_LaunchAll {
            get {
                return ResourceManager.GetString("Task.LaunchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch all selected tasks.
        /// </summary>
        internal static string Task_LaunchSelect {
            get {
                return ResourceManager.GetString("Task.LaunchSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem: source doesn&apos;t exist.
        /// </summary>
        internal static string Task_Popup_Add1 {
            get {
                return ResourceManager.GetString("Task.Popup.Add1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem: target doesn&apos;t exist.
        /// </summary>
        internal static string Task_Popup_Add2 {
            get {
                return ResourceManager.GetString("Task.Popup.Add2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem: source and target doesn&apos;t exist.
        /// </summary>
        internal static string Task_Popup_Add3 {
            get {
                return ResourceManager.GetString("Task.Popup.Add3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill out all the entries.
        /// </summary>
        internal static string Task_Popup_Add4 {
            get {
                return ResourceManager.GetString("Task.Popup.Add4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result.
        /// </summary>
        internal static string Task_Popup_Out {
            get {
                return ResourceManager.GetString("Task.Popup.Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem.
        /// </summary>
        internal static string Task_Popup_Warning {
            get {
                return ResourceManager.GetString("Task.Popup.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name :.
        /// </summary>
        internal static string Task_Prompt1 {
            get {
                return ResourceManager.GetString("Task.Prompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Path :.
        /// </summary>
        internal static string Task_Prompt2 {
            get {
                return ResourceManager.GetString("Task.Prompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target Path :.
        /// </summary>
        internal static string Task_Prompt3 {
            get {
                return ResourceManager.GetString("Task.Prompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        internal static string Task_Type1 {
            get {
                return ResourceManager.GetString("Task.Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        internal static string Task_Type2 {
            get {
                return ResourceManager.GetString("Task.Type2", resourceCulture);
            }
        }
    }
}
