//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDevSys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetDevSys.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading the configuration.
        /// </summary>
        internal static string AppConstants1 {
            get {
                return ResourceManager.GetString("AppConstants1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup with the same name already exists..
        /// </summary>
        internal static string BackupFactory1 {
            get {
                return ResourceManager.GetString("BackupFactory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported backup type..
        /// </summary>
        internal static string BackupJob1 {
            get {
                return ResourceManager.GetString("BackupJob1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change made..
        /// </summary>
        internal static string ConfigViewModel1 {
            get {
                return ResourceManager.GetString("ConfigViewModel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Json file path, language, real-time Json file path, and saved Json file path separated by commas:.
        /// </summary>
        internal static string ConfigViewText1 {
            get {
                return ResourceManager.GetString("ConfigViewText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Daily log file.
        /// </summary>
        internal static string ConfigViewText10 {
            get {
                return ResourceManager.GetString("ConfigViewText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Language.
        /// </summary>
        internal static string ConfigViewText11 {
            get {
                return ResourceManager.GetString("ConfigViewText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Real-time log file.
        /// </summary>
        internal static string ConfigViewText12 {
            get {
                return ResourceManager.GetString("ConfigViewText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Backup save file.
        /// </summary>
        internal static string ConfigViewText13 {
            get {
                return ResourceManager.GetString("ConfigViewText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Exit.
        /// </summary>
        internal static string ConfigViewText14 {
            get {
                return ResourceManager.GetString("ConfigViewText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid language. Please enter &apos;fr&apos; for French or &apos;en&apos; for English..
        /// </summary>
        internal static string ConfigViewText15 {
            get {
                return ResourceManager.GetString("ConfigViewText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change made. Please restart the application.
        /// </summary>
        internal static string ConfigViewText16 {
            get {
                return ResourceManager.GetString("ConfigViewText16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the main menu.
        /// </summary>
        internal static string ConfigViewText2 {
            get {
                return ResourceManager.GetString("ConfigViewText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or non-existent JSON file..
        /// </summary>
        internal static string ConfigViewText3 {
            get {
                return ResourceManager.GetString("ConfigViewText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice.
        /// </summary>
        internal static string ConfigViewText4 {
            get {
                return ResourceManager.GetString("ConfigViewText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new path for the log file:.
        /// </summary>
        internal static string ConfigViewText5 {
            get {
                return ResourceManager.GetString("ConfigViewText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new language (fr/en):.
        /// </summary>
        internal static string ConfigViewText6 {
            get {
                return ResourceManager.GetString("ConfigViewText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new path for the real-time log file:.
        /// </summary>
        internal static string ConfigViewText7 {
            get {
                return ResourceManager.GetString("ConfigViewText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new path for the backup save file:.
        /// </summary>
        internal static string ConfigViewText8 {
            get {
                return ResourceManager.GetString("ConfigViewText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which field would you like to edit?.
        /// </summary>
        internal static string ConfigViewText9 {
            get {
                return ResourceManager.GetString("ConfigViewText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------------------------------------------.
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete done..
        /// </summary>
        internal static string GestionTask1 {
            get {
                return ResourceManager.GetString("GestionTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist.
        /// </summary>
        internal static string GestionTask2 {
            get {
                return ResourceManager.GetString("GestionTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit done..
        /// </summary>
        internal static string GestionTask3 {
            get {
                return ResourceManager.GetString("GestionTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist.
        /// </summary>
        internal static string GestionTask4 {
            get {
                return ResourceManager.GetString("GestionTask4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New destination recorded.
        /// </summary>
        internal static string GestionTask5 {
            get {
                return ResourceManager.GetString("GestionTask5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New source recorded.
        /// </summary>
        internal static string GestionTask6 {
            get {
                return ResourceManager.GetString("GestionTask6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New type recorded.
        /// </summary>
        internal static string GestionTask7 {
            get {
                return ResourceManager.GetString("GestionTask7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Add a task.
        /// </summary>
        internal static string GestionTaskView1 {
            get {
                return ResourceManager.GetString("GestionTaskView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameters..
        /// </summary>
        internal static string GestionTaskView10 {
            get {
                return ResourceManager.GetString("GestionTaskView10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option..
        /// </summary>
        internal static string GestionTaskView11 {
            get {
                return ResourceManager.GetString("GestionTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the backup name:.
        /// </summary>
        internal static string GestionTaskView13 {
            get {
                return ResourceManager.GetString("GestionTaskView13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the source path:.
        /// </summary>
        internal static string GestionTaskView14 {
            get {
                return ResourceManager.GetString("GestionTaskView14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView15 {
            get {
                return ResourceManager.GetString("GestionTaskView15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the destination path:.
        /// </summary>
        internal static string GestionTaskView16 {
            get {
                return ResourceManager.GetString("GestionTaskView16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the backup type (A for full, B for differential):.
        /// </summary>
        internal static string GestionTaskView17 {
            get {
                return ResourceManager.GetString("GestionTaskView17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Delete a task.
        /// </summary>
        internal static string GestionTaskView18 {
            get {
                return ResourceManager.GetString("GestionTaskView18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Edit a task.
        /// </summary>
        internal static string GestionTaskView19 {
            get {
                return ResourceManager.GetString("GestionTaskView19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the file name, source path, destination path, and backup type separated by commas:.
        /// </summary>
        internal static string GestionTaskView2 {
            get {
                return ResourceManager.GetString("GestionTaskView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Exit.
        /// </summary>
        internal static string GestionTaskView20 {
            get {
                return ResourceManager.GetString("GestionTaskView20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the main menu..
        /// </summary>
        internal static string GestionTaskView21 {
            get {
                return ResourceManager.GetString("GestionTaskView21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView22 {
            get {
                return ResourceManager.GetString("GestionTaskView22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry. Please enter &apos;A&apos; or &apos;B&apos;..
        /// </summary>
        internal static string GestionTaskView23 {
            get {
                return ResourceManager.GetString("GestionTaskView23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups recorded.
        /// </summary>
        internal static string GestionTaskView24 {
            get {
                return ResourceManager.GetString("GestionTaskView24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the backup source? (y/n).
        /// </summary>
        internal static string GestionTaskView25 {
            get {
                return ResourceManager.GetString("GestionTaskView25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new path for the source:.
        /// </summary>
        internal static string GestionTaskView26 {
            get {
                return ResourceManager.GetString("GestionTaskView26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView27 {
            get {
                return ResourceManager.GetString("GestionTaskView27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the backup destination? (y/n).
        /// </summary>
        internal static string GestionTaskView28 {
            get {
                return ResourceManager.GetString("GestionTaskView28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new path for the destination:.
        /// </summary>
        internal static string GestionTaskView29 {
            get {
                return ResourceManager.GetString("GestionTaskView29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup successfully created..
        /// </summary>
        internal static string GestionTaskView3 {
            get {
                return ResourceManager.GetString("GestionTaskView3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView30 {
            get {
                return ResourceManager.GetString("GestionTaskView30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the backup type? (y/n).
        /// </summary>
        internal static string GestionTaskView31 {
            get {
                return ResourceManager.GetString("GestionTaskView31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new backup type (A Complete /B Differential):.
        /// </summary>
        internal static string GestionTaskView32 {
            get {
                return ResourceManager.GetString("GestionTaskView32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type, please enter A or B..
        /// </summary>
        internal static string GestionTaskView33 {
            get {
                return ResourceManager.GetString("GestionTaskView33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response, please enter &apos;y&apos; for yes or &apos;n&apos; for no..
        /// </summary>
        internal static string GestionTaskView34 {
            get {
                return ResourceManager.GetString("GestionTaskView34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create backup..
        /// </summary>
        internal static string GestionTaskView4 {
            get {
                return ResourceManager.GetString("GestionTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameters..
        /// </summary>
        internal static string GestionTaskView5 {
            get {
                return ResourceManager.GetString("GestionTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the backup ID to delete:.
        /// </summary>
        internal static string GestionTaskView6 {
            get {
                return ResourceManager.GetString("GestionTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID..
        /// </summary>
        internal static string GestionTaskView7 {
            get {
                return ResourceManager.GetString("GestionTaskView7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the backup ID to edit :.
        /// </summary>
        internal static string GestionTaskView8 {
            get {
                return ResourceManager.GetString("GestionTaskView8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID..
        /// </summary>
        internal static string GestionTaskView9 {
            get {
                return ResourceManager.GetString("GestionTaskView9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source folder does not exist..
        /// </summary>
        internal static string InterfaceStrategy1 {
            get {
                return ResourceManager.GetString("InterfaceStrategy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        internal static string JsonManager1 {
            get {
                return ResourceManager.GetString("JsonManager1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu:.
        /// </summary>
        internal static string MenuPrincipal1 {
            get {
                return ResourceManager.GetString("MenuPrincipal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Execute a task.
        /// </summary>
        internal static string MenuPrincipal2 {
            get {
                return ResourceManager.GetString("MenuPrincipal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Task management.
        /// </summary>
        internal static string MenuPrincipal3 {
            get {
                return ResourceManager.GetString("MenuPrincipal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Edit configuration.
        /// </summary>
        internal static string MenuPrincipal4 {
            get {
                return ResourceManager.GetString("MenuPrincipal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Exit.
        /// </summary>
        internal static string MenuPrincipal5 {
            get {
                return ResourceManager.GetString("MenuPrincipal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your choice (1-4):.
        /// </summary>
        internal static string MenuPrincipal6 {
            get {
                return ResourceManager.GetString("MenuPrincipal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the program....
        /// </summary>
        internal static string MenuPrincipal7 {
            get {
                return ResourceManager.GetString("MenuPrincipal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice. Please try again..
        /// </summary>
        internal static string MenuPrincipal8 {
            get {
                return ResourceManager.GetString("MenuPrincipal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Launch a task.
        /// </summary>
        internal static string RunTaskView1 {
            get {
                return ResourceManager.GetString("RunTaskView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string RunTaskView10 {
            get {
                return ResourceManager.GetString("RunTaskView10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup of all selected tasks finished successfully..
        /// </summary>
        internal static string RunTaskView11 {
            get {
                return ResourceManager.GetString("RunTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred during the backup of tasks..
        /// </summary>
        internal static string RunTaskView12 {
            get {
                return ResourceManager.GetString("RunTaskView12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RunTaskView13 {
            get {
                return ResourceManager.GetString("RunTaskView13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Launch multiple successive tasks.
        /// </summary>
        internal static string RunTaskView14 {
            get {
                return ResourceManager.GetString("RunTaskView14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Launch a list of tasks.
        /// </summary>
        internal static string RunTaskView15 {
            get {
                return ResourceManager.GetString("RunTaskView15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Exit.
        /// </summary>
        internal static string RunTaskView16 {
            get {
                return ResourceManager.GetString("RunTaskView16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end ID must be higher than the start ID..
        /// </summary>
        internal static string RunTaskView17 {
            get {
                return ResourceManager.GetString("RunTaskView17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the main menu.
        /// </summary>
        internal static string RunTaskView18 {
            get {
                return ResourceManager.GetString("RunTaskView18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified IDs are not valid..
        /// </summary>
        internal static string RunTaskView19 {
            get {
                return ResourceManager.GetString("RunTaskView19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the task ID you want to run.
        /// </summary>
        internal static string RunTaskView2 {
            get {
                return ResourceManager.GetString("RunTaskView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified ID is not valid. Please enter a numeric ID corresponding to an existing backup..
        /// </summary>
        internal static string RunTaskView20 {
            get {
                return ResourceManager.GetString("RunTaskView20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup done..
        /// </summary>
        internal static string RunTaskView3 {
            get {
                return ResourceManager.GetString("RunTaskView3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred.
        /// </summary>
        internal static string RunTaskView4 {
            get {
                return ResourceManager.GetString("RunTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the ID of the first and last task you want to perform, separated by a comma (example: 2,5):.
        /// </summary>
        internal static string RunTaskView5 {
            get {
                return ResourceManager.GetString("RunTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup done..
        /// </summary>
        internal static string RunTaskView6 {
            get {
                return ResourceManager.GetString("RunTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred..
        /// </summary>
        internal static string RunTaskView7 {
            get {
                return ResourceManager.GetString("RunTaskView7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter exactly two valid IDs, separated by a comma..
        /// </summary>
        internal static string RunTaskView8 {
            get {
                return ResourceManager.GetString("RunTaskView8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the IDs of the tasks you want to perform, separated by commas (example: 1,3,5):.
        /// </summary>
        internal static string RunTaskView9 {
            get {
                return ResourceManager.GetString("RunTaskView9", resourceCulture);
            }
        }
    }
}
