//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDevSys {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages_leandro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_leandro() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetDevSys.Messages.leandro", typeof(Messages_leandro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est pas bon.
        /// </summary>
        public static string AppConstants1 {
            get {
                return ResourceManager.GetString("AppConstants1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est pas bon.
        /// </summary>
        public static string BackupFactory1 {
            get {
                return ResourceManager.GetString("BackupFactory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est pas bon.
        /// </summary>
        public static string BackupJob1 {
            get {
                return ResourceManager.GetString("BackupJob1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le poulet est bon.
        /// </summary>
        public static string ConfigViewModel1 {
            get {
                return ResourceManager.GetString("ConfigViewModel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le poulet est cuit.
        /// </summary>
        public static string ConfigViewModel16 {
            get {
                return ResourceManager.GetString("ConfigViewModel16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regardes moi bien ce chemin du fichier Json, la langue, le chemin du fichier Json en temps réel, et le chemin du fichier Json sauvegardé séparés par des virgules:&quot;.
        /// </summary>
        public static string ConfigViewText1 {
            get {
                return ResourceManager.GetString("ConfigViewText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Fichier de logs journaliers.
        /// </summary>
        public static string ConfigViewText10 {
            get {
                return ResourceManager.GetString("ConfigViewText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Langue.
        /// </summary>
        public static string ConfigViewText11 {
            get {
                return ResourceManager.GetString("ConfigViewText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Fichier de logs en temps réel.
        /// </summary>
        public static string ConfigViewText12 {
            get {
                return ResourceManager.GetString("ConfigViewText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Fichier de sauvegarde des poulets.
        /// </summary>
        public static string ConfigViewText13 {
            get {
                return ResourceManager.GetString("ConfigViewText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5. Quitter.
        /// </summary>
        public static string ConfigViewText14 {
            get {
                return ResourceManager.GetString("ConfigViewText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est pas bon.
        /// </summary>
        public static string ConfigViewText15 {
            get {
                return ResourceManager.GetString("ConfigViewText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour au Portugal.
        /// </summary>
        public static string ConfigViewText2 {
            get {
                return ResourceManager.GetString("ConfigViewText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est pas bon.
        /// </summary>
        public static string ConfigViewText3 {
            get {
                return ResourceManager.GetString("ConfigViewText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est pas bon.
        /// </summary>
        public static string ConfigViewText4 {
            get {
                return ResourceManager.GetString("ConfigViewText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre le nouveau chemin pour le fichier de log :.
        /// </summary>
        public static string ConfigViewText5 {
            get {
                return ResourceManager.GetString("ConfigViewText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre pas la nouvelle langue (LEANDRO ou rien) :.
        /// </summary>
        public static string ConfigViewText6 {
            get {
                return ResourceManager.GetString("ConfigViewText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre le nouveau chemin pour le fichier de log en temps reel :.
        /// </summary>
        public static string ConfigViewText7 {
            get {
                return ResourceManager.GetString("ConfigViewText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre le nouveau chemin pour le fichier de sauvegarde des backup :.
        /// </summary>
        public static string ConfigViewText8 {
            get {
                return ResourceManager.GetString("ConfigViewText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wesh mon reuf t&apos;édites quoi ?.
        /// </summary>
        public static string ConfigViewText9 {
            get {
                return ResourceManager.GetString("ConfigViewText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----------------------------------------------------------------------------.
        /// </summary>
        public static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le poulet a quoicoucuit..
        /// </summary>
        public static string GestionTask1 {
            get {
                return ResourceManager.GetString("GestionTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cheeeeef le fichier existe pas tu troll.
        /// </summary>
        public static string GestionTask2 {
            get {
                return ResourceManager.GetString("GestionTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finito.
        /// </summary>
        public static string GestionTask3 {
            get {
                return ResourceManager.GetString("GestionTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cheeeeef le fichier existe pas tu troll.
        /// </summary>
        public static string GestionTask4 {
            get {
                return ResourceManager.GetString("GestionTask4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle destination enregistrée.
        /// </summary>
        public static string GestionTask5 {
            get {
                return ResourceManager.GetString("GestionTask5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle source enregistrée.
        /// </summary>
        public static string GestionTask6 {
            get {
                return ResourceManager.GetString("GestionTask6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau type enregistré.
        /// </summary>
        public static string GestionTask7 {
            get {
                return ResourceManager.GetString("GestionTask7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Ajouter une tache.
        /// </summary>
        public static string GestionTaskView1 {
            get {
                return ResourceManager.GetString("GestionTaskView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chef ce poulet est pas cuit.
        /// </summary>
        public static string GestionTaskView10 {
            get {
                return ResourceManager.GetString("GestionTaskView10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est pas bon.
        /// </summary>
        public static string GestionTaskView11 {
            get {
                return ResourceManager.GetString("GestionTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre le nom de sauvegarde :.
        /// </summary>
        public static string GestionTaskView13 {
            get {
                return ResourceManager.GetString("GestionTaskView13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre le chemin source :.
        /// </summary>
        public static string GestionTaskView14 {
            get {
                return ResourceManager.GetString("GestionTaskView14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wesh mon reuf c&apos;est quoi ce chemin.
        /// </summary>
        public static string GestionTaskView15 {
            get {
                return ResourceManager.GetString("GestionTaskView15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre le chemin de destination :.
        /// </summary>
        public static string GestionTaskView16 {
            get {
                return ResourceManager.GetString("GestionTaskView16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre le type de sauvegarde (A pour complète, B pour differentielle) :.
        /// </summary>
        public static string GestionTaskView17 {
            get {
                return ResourceManager.GetString("GestionTaskView17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Supprimer une tache.
        /// </summary>
        public static string GestionTaskView18 {
            get {
                return ResourceManager.GetString("GestionTaskView18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Modifier une tache.
        /// </summary>
        public static string GestionTaskView19 {
            get {
                return ResourceManager.GetString("GestionTaskView19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regardes moi ce nom du fichier, le chemin source, le chemin de destination, et le type de sauvegarde séparés par des virgules:.
        /// </summary>
        public static string GestionTaskView2 {
            get {
                return ResourceManager.GetString("GestionTaskView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Quitter.
        /// </summary>
        public static string GestionTaskView20 {
            get {
                return ResourceManager.GetString("GestionTaskView20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour au Portugal.
        /// </summary>
        public static string GestionTaskView21 {
            get {
                return ResourceManager.GetString("GestionTaskView21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce chemin est pas cuit.
        /// </summary>
        public static string GestionTaskView22 {
            get {
                return ResourceManager.GetString("GestionTaskView22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chef c&apos;est A ou B t&apos;es bête ou quoi.
        /// </summary>
        public static string GestionTaskView23 {
            get {
                return ResourceManager.GetString("GestionTaskView23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quoicouchef t&apos;as pas de quoicousave.
        /// </summary>
        public static string GestionTaskView24 {
            get {
                return ResourceManager.GetString("GestionTaskView24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tu changes la source ? T&apos;es indécis ? .
        /// </summary>
        public static string GestionTaskView25 {
            get {
                return ResourceManager.GetString("GestionTaskView25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ... entre le nouveau chemin pour la source....
        /// </summary>
        public static string GestionTaskView26 {
            get {
                return ResourceManager.GetString("GestionTaskView26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin non valide, veuillez entrer un chemin valide..
        /// </summary>
        public static string GestionTaskView27 {
            get {
                return ResourceManager.GetString("GestionTaskView27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si tu changes la destination t&apos;es un quoicoutrolleur.
        /// </summary>
        public static string GestionTaskView28 {
            get {
                return ResourceManager.GetString("GestionTaskView28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok entre le nouveau chemin pour la destination :.
        /// </summary>
        public static string GestionTaskView29 {
            get {
                return ResourceManager.GetString("GestionTaskView29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le poulet est succulent.
        /// </summary>
        public static string GestionTaskView3 {
            get {
                return ResourceManager.GetString("GestionTaskView3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est succulent.
        /// </summary>
        public static string GestionTaskView30 {
            get {
                return ResourceManager.GetString("GestionTaskView30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tu changes le type de sauvegarde ?.
        /// </summary>
        public static string GestionTaskView31 {
            get {
                return ResourceManager.GetString("GestionTaskView31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vazy chef vazy dis moi.
        /// </summary>
        public static string GestionTaskView32 {
            get {
                return ResourceManager.GetString("GestionTaskView32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cheeeeef tu troll.
        /// </summary>
        public static string GestionTaskView33 {
            get {
                return ResourceManager.GetString("GestionTaskView33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeef c&apos;est pas bon.
        /// </summary>
        public static string GestionTaskView34 {
            get {
                return ResourceManager.GetString("GestionTaskView34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regarde moi bien comment ce caca est mauvais.
        /// </summary>
        public static string GestionTaskView4 {
            get {
                return ResourceManager.GetString("GestionTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C&apos;est quoi ce caca là.
        /// </summary>
        public static string GestionTaskView5 {
            get {
                return ResourceManager.GetString("GestionTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C&apos;est quoi l&apos;poulet à éliminer.
        /// </summary>
        public static string GestionTaskView6 {
            get {
                return ResourceManager.GetString("GestionTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CHEEEEEEEEEEEEEEEEEEEEEEF.
        /// </summary>
        public static string GestionTaskView7 {
            get {
                return ResourceManager.GetString("GestionTaskView7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez l&apos;id de la tâche de sauvegarde à modifier :.
        /// </summary>
        public static string GestionTaskView8 {
            get {
                return ResourceManager.GetString("GestionTaskView8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant invalide..
        /// </summary>
        public static string GestionTaskView9 {
            get {
                return ResourceManager.GetString("GestionTaskView9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca est dégeu.
        /// </summary>
        public static string InterfaceStrategy1 {
            get {
                return ResourceManager.GetString("InterfaceStrategy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chef le fichier pue sa mère.
        /// </summary>
        public static string JsonManager1 {
            get {
                return ResourceManager.GetString("JsonManager1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portugal :.
        /// </summary>
        public static string MenuPrincipal1 {
            get {
                return ResourceManager.GetString("MenuPrincipal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Exécuter un poulet.
        /// </summary>
        public static string MenuPrincipal2 {
            get {
                return ResourceManager.GetString("MenuPrincipal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Gestion des poulet.
        /// </summary>
        public static string MenuPrincipal3 {
            get {
                return ResourceManager.GetString("MenuPrincipal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Quoicouparamètres.
        /// </summary>
        public static string MenuPrincipal4 {
            get {
                return ResourceManager.GetString("MenuPrincipal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Go Crypto.
        /// </summary>
        public static string MenuPrincipal5 {
            get {
                return ResourceManager.GetString("MenuPrincipal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ou tu vas chef ?.
        /// </summary>
        public static string MenuPrincipal6 {
            get {
                return ResourceManager.GetString("MenuPrincipal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptotage en cours....
        /// </summary>
        public static string MenuPrincipal7 {
            get {
                return ResourceManager.GetString("MenuPrincipal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cheeeeeeeeeeef c&apos;est quoi ca ?.
        /// </summary>
        public static string MenuPrincipal8 {
            get {
                return ResourceManager.GetString("MenuPrincipal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Lancer un poulet.
        /// </summary>
        public static string RunTaskView1 {
            get {
                return ResourceManager.GetString("RunTaskView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C&apos;est quoi ce poulet wesh.
        /// </summary>
        public static string RunTaskView10 {
            get {
                return ResourceManager.GetString("RunTaskView10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les poulets sont sauvegardés.
        /// </summary>
        public static string RunTaskView11 {
            get {
                return ResourceManager.GetString("RunTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca des poulets est pas bon.
        /// </summary>
        public static string RunTaskView12 {
            get {
                return ResourceManager.GetString("RunTaskView12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chef c&apos;est quoi cette erreur.
        /// </summary>
        public static string RunTaskView13 {
            get {
                return ResourceManager.GetString("RunTaskView13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Lancer PLUSIEURS poulets.
        /// </summary>
        public static string RunTaskView14 {
            get {
                return ResourceManager.GetString("RunTaskView14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Lancer un DEATH NOTE de poulets.
        /// </summary>
        public static string RunTaskView15 {
            get {
                return ResourceManager.GetString("RunTaskView15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Retour au Portugal.
        /// </summary>
        public static string RunTaskView16 {
            get {
                return ResourceManager.GetString("RunTaskView16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C&apos;est pas dans le bon ordre wesh.
        /// </summary>
        public static string RunTaskView17 {
            get {
                return ResourceManager.GetString("RunTaskView17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour au Portugal.
        /// </summary>
        public static string RunTaskView18 {
            get {
                return ResourceManager.GetString("RunTaskView18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C&apos;est quoi ce poulet ?.
        /// </summary>
        public static string RunTaskView19 {
            get {
                return ResourceManager.GetString("RunTaskView19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre l&apos;ID du poulet à lancer.
        /// </summary>
        public static string RunTaskView2 {
            get {
                return ResourceManager.GetString("RunTaskView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ca corresponds à aucun poulet ca chef.
        /// </summary>
        public static string RunTaskView20 {
            get {
                return ResourceManager.GetString("RunTaskView20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun poulet enregistré.
        /// </summary>
        public static string RunTaskView21 {
            get {
                return ResourceManager.GetString("RunTaskView21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poulet exécuté.
        /// </summary>
        public static string RunTaskView3 {
            get {
                return ResourceManager.GetString("RunTaskView3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chef c&apos;est quoi ce quoicoublème.
        /// </summary>
        public static string RunTaskView4 {
            get {
                return ResourceManager.GetString("RunTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre l&apos;ID du premier et dernier poulet que tu veux exécuter, séparés par une virgule (genre: 2,5):.
        /// </summary>
        public static string RunTaskView5 {
            get {
                return ResourceManager.GetString("RunTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poulet executé..
        /// </summary>
        public static string RunTaskView6 {
            get {
                return ResourceManager.GetString("RunTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caca du poulet est pas bon..
        /// </summary>
        public static string RunTaskView7 {
            get {
                return ResourceManager.GetString("RunTaskView7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chef c&apos;est pas dur tu fous deux ID avec une virgule quoi.
        /// </summary>
        public static string RunTaskView8 {
            get {
                return ResourceManager.GetString("RunTaskView8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entre les ID des poulets que tu veux exécuter, séparés par des virgules (genre: 1,3,5):.
        /// </summary>
        public static string RunTaskView9 {
            get {
                return ResourceManager.GetString("RunTaskView9", resourceCulture);
            }
        }
    }
}
