//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDevSys {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetDevSys.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while reading the configuration.
        /// </summary>
        internal static string AppConstants1 {
            get {
                return ResourceManager.GetString("AppConstants1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A backup with the same name already exists..
        /// </summary>
        internal static string BackupFactory1 {
            get {
                return ResourceManager.GetString("BackupFactory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsupported backup type..
        /// </summary>
        internal static string BackupJob1 {
            get {
                return ResourceManager.GetString("BackupJob1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft Folder dooesn&apos;t exist. Downloading....
        /// </summary>
        internal static string ConfigText1 {
            get {
                return ResourceManager.GetString("ConfigText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download complete. Extracting....
        /// </summary>
        internal static string ConfigText2 {
            get {
                return ResourceManager.GetString("ConfigText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract complete. Folders availables in.
        /// </summary>
        internal static string ConfigText3 {
            get {
                return ResourceManager.GetString("ConfigText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured :.
        /// </summary>
        internal static string ConfigText4 {
            get {
                return ResourceManager.GetString("ConfigText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft folder already exists..
        /// </summary>
        internal static string ConfigText5 {
            get {
                return ResourceManager.GetString("ConfigText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change made..
        /// </summary>
        internal static string ConfigViewModel1 {
            get {
                return ResourceManager.GetString("ConfigViewModel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change made. Please restart the application.
        /// </summary>
        internal static string ConfigViewModel16 {
            get {
                return ResourceManager.GetString("ConfigViewModel16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the Json file path, language, real-time Json file path, and saved Json file path separated by commas:.
        /// </summary>
        internal static string ConfigViewText1 {
            get {
                return ResourceManager.GetString("ConfigViewText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Daily log file.
        /// </summary>
        internal static string ConfigViewText10 {
            get {
                return ResourceManager.GetString("ConfigViewText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Language.
        /// </summary>
        internal static string ConfigViewText11 {
            get {
                return ResourceManager.GetString("ConfigViewText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Real-time log file.
        /// </summary>
        internal static string ConfigViewText12 {
            get {
                return ResourceManager.GetString("ConfigViewText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Backup save file.
        /// </summary>
        internal static string ConfigViewText13 {
            get {
                return ResourceManager.GetString("ConfigViewText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9. Exit.
        /// </summary>
        internal static string ConfigViewText14 {
            get {
                return ResourceManager.GetString("ConfigViewText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid language. Please enter &apos;fr&apos; for French or &apos;en&apos; for English..
        /// </summary>
        internal static string ConfigViewText15 {
            get {
                return ResourceManager.GetString("ConfigViewText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter extension type for logs (.json/.xml) :.
        /// </summary>
        internal static string ConfigViewText16 {
            get {
                return ResourceManager.GetString("ConfigViewText16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid extension. Please enter &apos;.json&apos; or &apos;.xml&apos;..
        /// </summary>
        internal static string ConfigViewText17 {
            get {
                return ResourceManager.GetString("ConfigViewText17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5. Log extension type.
        /// </summary>
        internal static string ConfigViewText18 {
            get {
                return ResourceManager.GetString("ConfigViewText18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter an extension type.
        /// </summary>
        internal static string ConfigViewText19 {
            get {
                return ResourceManager.GetString("ConfigViewText19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return to the main menu.
        /// </summary>
        internal static string ConfigViewText2 {
            get {
                return ResourceManager.GetString("ConfigViewText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid extension.
        /// </summary>
        internal static string ConfigViewText20 {
            get {
                return ResourceManager.GetString("ConfigViewText20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the path to cryptosoft.
        /// </summary>
        internal static string ConfigViewText21 {
            get {
                return ResourceManager.GetString("ConfigViewText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid path.
        /// </summary>
        internal static string ConfigViewText22 {
            get {
                return ResourceManager.GetString("ConfigViewText22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6. Add an extension to encrypt.
        /// </summary>
        internal static string ConfigViewText23 {
            get {
                return ResourceManager.GetString("ConfigViewText23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7. Edit cryptosoft path.
        /// </summary>
        internal static string ConfigViewText24 {
            get {
                return ResourceManager.GetString("ConfigViewText24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The configuration has been reset..
        /// </summary>
        internal static string ConfigViewText25 {
            get {
                return ResourceManager.GetString("ConfigViewText25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the id to be deleted.
        /// </summary>
        internal static string ConfigViewText26 {
            get {
                return ResourceManager.GetString("ConfigViewText26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid identifier.
        /// </summary>
        internal static string ConfigViewText27 {
            get {
                return ResourceManager.GetString("ConfigViewText27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8. Delete an extension to be encrypted.
        /// </summary>
        internal static string ConfigViewText28 {
            get {
                return ResourceManager.GetString("ConfigViewText28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid or non-existent JSON file..
        /// </summary>
        internal static string ConfigViewText3 {
            get {
                return ResourceManager.GetString("ConfigViewText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid choice.
        /// </summary>
        internal static string ConfigViewText4 {
            get {
                return ResourceManager.GetString("ConfigViewText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new path for the log file:.
        /// </summary>
        internal static string ConfigViewText5 {
            get {
                return ResourceManager.GetString("ConfigViewText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new language (fr/en):.
        /// </summary>
        internal static string ConfigViewText6 {
            get {
                return ResourceManager.GetString("ConfigViewText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new path for the real-time log file:.
        /// </summary>
        internal static string ConfigViewText7 {
            get {
                return ResourceManager.GetString("ConfigViewText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new path for the backup save file:.
        /// </summary>
        internal static string ConfigViewText8 {
            get {
                return ResourceManager.GetString("ConfigViewText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which field would you like to edit?.
        /// </summary>
        internal static string ConfigViewText9 {
            get {
                return ResourceManager.GetString("ConfigViewText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ----------------------------------------------------------------------------.
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete done..
        /// </summary>
        internal static string GestionTask1 {
            get {
                return ResourceManager.GetString("GestionTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file does not exist.
        /// </summary>
        internal static string GestionTask2 {
            get {
                return ResourceManager.GetString("GestionTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit done..
        /// </summary>
        internal static string GestionTask3 {
            get {
                return ResourceManager.GetString("GestionTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file does not exist.
        /// </summary>
        internal static string GestionTask4 {
            get {
                return ResourceManager.GetString("GestionTask4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New destination recorded.
        /// </summary>
        internal static string GestionTask5 {
            get {
                return ResourceManager.GetString("GestionTask5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New source recorded.
        /// </summary>
        internal static string GestionTask6 {
            get {
                return ResourceManager.GetString("GestionTask6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New type recorded.
        /// </summary>
        internal static string GestionTask7 {
            get {
                return ResourceManager.GetString("GestionTask7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Add a task.
        /// </summary>
        internal static string GestionTaskView1 {
            get {
                return ResourceManager.GetString("GestionTaskView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect parameters..
        /// </summary>
        internal static string GestionTaskView10 {
            get {
                return ResourceManager.GetString("GestionTaskView10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid option..
        /// </summary>
        internal static string GestionTaskView11 {
            get {
                return ResourceManager.GetString("GestionTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the backup name:.
        /// </summary>
        internal static string GestionTaskView13 {
            get {
                return ResourceManager.GetString("GestionTaskView13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the source path:.
        /// </summary>
        internal static string GestionTaskView14 {
            get {
                return ResourceManager.GetString("GestionTaskView14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView15 {
            get {
                return ResourceManager.GetString("GestionTaskView15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the destination path:.
        /// </summary>
        internal static string GestionTaskView16 {
            get {
                return ResourceManager.GetString("GestionTaskView16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the backup type (A for full, B for differential):.
        /// </summary>
        internal static string GestionTaskView17 {
            get {
                return ResourceManager.GetString("GestionTaskView17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Delete a task.
        /// </summary>
        internal static string GestionTaskView18 {
            get {
                return ResourceManager.GetString("GestionTaskView18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Edit a task.
        /// </summary>
        internal static string GestionTaskView19 {
            get {
                return ResourceManager.GetString("GestionTaskView19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the file name, source path, destination path, and backup type separated by commas:.
        /// </summary>
        internal static string GestionTaskView2 {
            get {
                return ResourceManager.GetString("GestionTaskView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Exit.
        /// </summary>
        internal static string GestionTaskView20 {
            get {
                return ResourceManager.GetString("GestionTaskView20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return to the main menu..
        /// </summary>
        internal static string GestionTaskView21 {
            get {
                return ResourceManager.GetString("GestionTaskView21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView22 {
            get {
                return ResourceManager.GetString("GestionTaskView22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entry. Please enter &apos;A&apos; or &apos;B&apos;..
        /// </summary>
        internal static string GestionTaskView23 {
            get {
                return ResourceManager.GetString("GestionTaskView23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backups recorded.
        /// </summary>
        internal static string GestionTaskView24 {
            get {
                return ResourceManager.GetString("GestionTaskView24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to change the backup source? (y/n).
        /// </summary>
        internal static string GestionTaskView25 {
            get {
                return ResourceManager.GetString("GestionTaskView25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new path for the source:.
        /// </summary>
        internal static string GestionTaskView26 {
            get {
                return ResourceManager.GetString("GestionTaskView26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView27 {
            get {
                return ResourceManager.GetString("GestionTaskView27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to change the backup destination? (y/n).
        /// </summary>
        internal static string GestionTaskView28 {
            get {
                return ResourceManager.GetString("GestionTaskView28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new path for the destination:.
        /// </summary>
        internal static string GestionTaskView29 {
            get {
                return ResourceManager.GetString("GestionTaskView29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup successfully created..
        /// </summary>
        internal static string GestionTaskView3 {
            get {
                return ResourceManager.GetString("GestionTaskView3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid path, please enter a valid path..
        /// </summary>
        internal static string GestionTaskView30 {
            get {
                return ResourceManager.GetString("GestionTaskView30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to change the backup type? (y/n).
        /// </summary>
        internal static string GestionTaskView31 {
            get {
                return ResourceManager.GetString("GestionTaskView31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new backup type (A Complete /B Differential):.
        /// </summary>
        internal static string GestionTaskView32 {
            get {
                return ResourceManager.GetString("GestionTaskView32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid type, please enter A or B..
        /// </summary>
        internal static string GestionTaskView33 {
            get {
                return ResourceManager.GetString("GestionTaskView33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid response, please enter &apos;y&apos; for yes or &apos;n&apos; for no..
        /// </summary>
        internal static string GestionTaskView34 {
            get {
                return ResourceManager.GetString("GestionTaskView34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Backup name already exists or is null.
        /// </summary>
        internal static string GestionTaskView35 {
            get {
                return ResourceManager.GetString("GestionTaskView35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to create backup..
        /// </summary>
        internal static string GestionTaskView4 {
            get {
                return ResourceManager.GetString("GestionTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect parameters..
        /// </summary>
        internal static string GestionTaskView5 {
            get {
                return ResourceManager.GetString("GestionTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the backup ID to delete:.
        /// </summary>
        internal static string GestionTaskView6 {
            get {
                return ResourceManager.GetString("GestionTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ID..
        /// </summary>
        internal static string GestionTaskView7 {
            get {
                return ResourceManager.GetString("GestionTaskView7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the backup ID to edit :.
        /// </summary>
        internal static string GestionTaskView8 {
            get {
                return ResourceManager.GetString("GestionTaskView8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ID..
        /// </summary>
        internal static string GestionTaskView9 {
            get {
                return ResourceManager.GetString("GestionTaskView9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name is already taken. Please enter another..
        /// </summary>
        internal static string GestionTaskViewText35 {
            get {
                return ResourceManager.GetString("GestionTaskViewText35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source folder does not exist..
        /// </summary>
        internal static string InterfaceStrategy1 {
            get {
                return ResourceManager.GetString("InterfaceStrategy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task interrupted : blocking process detected.
        /// </summary>
        internal static string InterfaceStrategy2 {
            get {
                return ResourceManager.GetString("InterfaceStrategy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file does not exist..
        /// </summary>
        internal static string JsonManager1 {
            get {
                return ResourceManager.GetString("JsonManager1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Menu:.
        /// </summary>
        internal static string MenuPrincipal1 {
            get {
                return ResourceManager.GetString("MenuPrincipal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Execute a task.
        /// </summary>
        internal static string MenuPrincipal2 {
            get {
                return ResourceManager.GetString("MenuPrincipal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Task management.
        /// </summary>
        internal static string MenuPrincipal3 {
            get {
                return ResourceManager.GetString("MenuPrincipal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Edit configuration.
        /// </summary>
        internal static string MenuPrincipal4 {
            get {
                return ResourceManager.GetString("MenuPrincipal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Exit.
        /// </summary>
        internal static string MenuPrincipal5 {
            get {
                return ResourceManager.GetString("MenuPrincipal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your choice (1-4):.
        /// </summary>
        internal static string MenuPrincipal6 {
            get {
                return ResourceManager.GetString("MenuPrincipal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exiting the program....
        /// </summary>
        internal static string MenuPrincipal7 {
            get {
                return ResourceManager.GetString("MenuPrincipal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid choice. Please try again..
        /// </summary>
        internal static string MenuPrincipal8 {
            get {
                return ResourceManager.GetString("MenuPrincipal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Launch a task.
        /// </summary>
        internal static string RunTaskView1 {
            get {
                return ResourceManager.GetString("RunTaskView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid input.
        /// </summary>
        internal static string RunTaskView10 {
            get {
                return ResourceManager.GetString("RunTaskView10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup of all selected tasks finished successfully..
        /// </summary>
        internal static string RunTaskView11 {
            get {
                return ResourceManager.GetString("RunTaskView11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A problem occurred during the backup of tasks..
        /// </summary>
        internal static string RunTaskView12 {
            get {
                return ResourceManager.GetString("RunTaskView12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string RunTaskView13 {
            get {
                return ResourceManager.GetString("RunTaskView13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Launch multiple successive tasks.
        /// </summary>
        internal static string RunTaskView14 {
            get {
                return ResourceManager.GetString("RunTaskView14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Launch a list of tasks.
        /// </summary>
        internal static string RunTaskView15 {
            get {
                return ResourceManager.GetString("RunTaskView15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4. Exit.
        /// </summary>
        internal static string RunTaskView16 {
            get {
                return ResourceManager.GetString("RunTaskView16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The end ID must be higher than the start ID..
        /// </summary>
        internal static string RunTaskView17 {
            get {
                return ResourceManager.GetString("RunTaskView17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return to the main menu.
        /// </summary>
        internal static string RunTaskView18 {
            get {
                return ResourceManager.GetString("RunTaskView18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified IDs are not valid..
        /// </summary>
        internal static string RunTaskView19 {
            get {
                return ResourceManager.GetString("RunTaskView19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the task ID you want to run.
        /// </summary>
        internal static string RunTaskView2 {
            get {
                return ResourceManager.GetString("RunTaskView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified ID is not valid. Please enter a numeric ID corresponding to an existing backup..
        /// </summary>
        internal static string RunTaskView20 {
            get {
                return ResourceManager.GetString("RunTaskView20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have no saved task.
        /// </summary>
        internal static string RunTaskView21 {
            get {
                return ResourceManager.GetString("RunTaskView21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task blocked : blocking process interrupted.
        /// </summary>
        internal static string RunTaskView22 {
            get {
                return ResourceManager.GetString("RunTaskView22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup done..
        /// </summary>
        internal static string RunTaskView3 {
            get {
                return ResourceManager.GetString("RunTaskView3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A problem occurred.
        /// </summary>
        internal static string RunTaskView4 {
            get {
                return ResourceManager.GetString("RunTaskView4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the ID of the first and last task you want to perform, separated by a comma (example: 2,5):.
        /// </summary>
        internal static string RunTaskView5 {
            get {
                return ResourceManager.GetString("RunTaskView5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup done..
        /// </summary>
        internal static string RunTaskView6 {
            get {
                return ResourceManager.GetString("RunTaskView6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A problem occurred..
        /// </summary>
        internal static string RunTaskView7 {
            get {
                return ResourceManager.GetString("RunTaskView7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid input. Please enter exactly two valid IDs, separated by a comma..
        /// </summary>
        internal static string RunTaskView8 {
            get {
                return ResourceManager.GetString("RunTaskView8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the IDs of the tasks you want to perform, separated by commas (example: 1,3,5):.
        /// </summary>
        internal static string RunTaskView9 {
            get {
                return ResourceManager.GetString("RunTaskView9", resourceCulture);
            }
        }
    }
}
